# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1385569845);
user_pref("app.update.lastUpdateTime.background-update-timer", 1385569723);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1385569968);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1385572885);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1385569261);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131112160018");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 7991);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "20131112160018");
user_pref("browser.startup.homepage_override.mstone", "25.0.1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1385655278542");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1385568878542");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1465);
user_pref("datareporting.sessions.current.main", 483);
user_pref("datareporting.sessions.current.startTime", "1385575022961");
user_pref("datareporting.sessions.current.totalTime", 9);
user_pref("datareporting.sessions.currentIndex", 14);
user_pref("datareporting.sessions.previous.0", "{\"s\":1385568871580,\"a\":2,\"t\":22,\"c\":true,\"m\":3,\"fp\":1427,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1385568897088,\"a\":34,\"t\":181,\"c\":true,\"m\":480,\"fp\":1470,\"sr\":5480}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1385570392213,\"a\":88,\"t\":2280,\"c\":true,\"m\":515,\"fp\":3168,\"sr\":3985}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1385572680299,\"a\":8,\"t\":81,\"c\":true,\"m\":749,\"fp\":1803,\"sr\":53450}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1385572763858,\"a\":63,\"t\":2187,\"c\":true,\"m\":499,\"fp\":1536,\"sr\":8048}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1385574952601,\"a\":2,\"t\":16,\"c\":true,\"m\":402,\"fp\":1186,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1385569079495,\"a\":10,\"t\":58,\"c\":true,\"m\":680,\"fp\":1783,\"sr\":5787}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1385569140191,\"a\":33,\"t\":193,\"c\":true,\"m\":520,\"fp\":1644,\"sr\":5848}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1385569335534,\"a\":4,\"t\":19,\"c\":true,\"m\":810,\"fp\":1915,\"sr\":7616}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1385569413412,\"a\":1,\"t\":3,\"c\":true,\"m\":491,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1385569591006,\"a\":62,\"t\":428,\"c\":true,\"m\":2652,\"fp\":55552,\"sr\":59370}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1385570021248,\"a\":2,\"t\":8,\"c\":true,\"m\":608,\"fp\":3514,\"sr\":4201}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1385570031434,\"a\":6,\"t\":34,\"c\":true,\"m\":483,\"fp\":3140,\"sr\":3929}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1385570066854,\"a\":7,\"t\":32,\"c\":false,\"m\":468,\"fp\":3111,\"sr\":3989}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"25.0.1\"}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"wrc@avast.com\":{\"descriptor\":\"C:\\\\Program Files\\\\AVAST Software\\\\Avast\\\\WebRep\\\\FF\",\"mtime\":1378815195391,\"rdfTime\":1377848682000}}},{\"name\":\"app-global\",\"addons\":{\"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\",\"mtime\":1381811856993,\"rdfTime\":1381305482000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1385568623188,\"rdfTime\":1384306527000}}}]");
user_pref("extensions.lastAppVersion", "25.0.1");
user_pref("extensions.lastPlatformVersion", "25.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131112160018");
user_pref("gecko.mstone", "25.0.1");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1385570844);
user_pref("intl.charsetmenu.browser.cache", "windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1385570845);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.bookmark_page", false);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.browser.homepage.disable_button.restore_default", false);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.lastversion", "1.27.0");
user_pref("services.sync.nextSync", 0);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1385570845);
user_pref("toolkit.startup.last_success", 1385575023);
user_pref("toolkit.telemetry.previousBuildID", "20131112160018");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1388160906);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
